lib/util/util.js

Just run in this issue.
At my machine:
```
stefan @ stefan-mac: ~/Desktop/sitespeed-test
> java -version                                          [12:50:24]
openjdk version "1.7.0-jdk7u4-b21"
OpenJDK Runtime Environment (build 1.7.0-jdk7u4-b21-20120427)
OpenJDK 64-Bit Server VM (build 23.0-b21, mixed mode)
```
So `matches` becomes `null` and sitespeed is crashing. Fixed it in this PR.

Fix for exception throwing Java version check

---

lib/util/util.js
test/util/utilTest.js

Fixes #651 
I run into some issues with certain characters on URI that where clashing with graphite functionality or caused parsing issues for grafana when trying to retrieve data from graphite
The characters are:
* pipe (|)
* comma (,)
* plus (+)
... they are replaced by a ```_``` (as the others are)

enhanced the getGraphiteURLKey function to replace additional characters

---

lib/analyzeOneSite.js

Looks like this wiring must have gotten missed when the feature was implemented.

When analyzing a single page, pass basic auth credentials if configured.

---

conf/defaultConfig.js
lib/cli.js
lib/graphite/graphiteCollector.js

This should fix issue #651.
Crawling **http://www.jeroenvdb.be** creates
````
sitespeed.io.http.www_jeroenvdb_be.slash.*
sitespeed.io.summary.http.www_jeroenvdb_be.slash.*
````
instead of www_jeroenvdb_be and www.jeroenvdb.be:
````
sitespeed.io.http.www_jeroenvdb_be.slash.*
sitespeed.io.summary.www.jeroenvdb.be.*
````

#651 Create same Graphite namespace structure for the domain url as for per-page metrics

---

lib/analyze/headless.js

Similar issue to #724.
This one fixes the usage of " --browser headless" with basic auth and request headers.

All args to the headless script should be passed in the right order

---

lib/util/util.js

We use query string to toggle things like ads and Optimizely.  The tests are run against the same URL's with ads on and off.  I noticed our scores seemed a little too forgiving for a site with ads.  It looks like query strings aren't taken into account when sending the data to Graphite.
This change combines the query string to an object which then converts it to an underscore delimited string.  It takes into account an empty value and filters empty strings when returning the `getGraphiteURLKey`.

use query string in url for graphite

---

lib/util/util.js

This fixes #805.
Basically if `--headless slimerjs` is passed, then it calls `slimerjs --version` instead of `phantomjs --version` when getting version info. This means when `--headless slimerjs` is specified, the phantomjs bin is actually never called.

ensure running slimerjs doesn't require phantomjs

---

tools/docker-compose.yml
tools/graphite.sh
tools/influxdb.sh

Added docker-compose.yml for #908 
Mac steps
```
cd tools
docker-compose up -d
docker-machine ls
```
Note IP address from docker-machine command and use that for the url in grafana's data source setup.

#908 - Adding docker-compose.yml for testing grafana, graphite, and influxdb

---

lib/plugins/html/templates/url/coach/index.jade

Notice the <br> tag was printed due to being escaped by default.

Unescaping <br> in page summary report for dns-prefetch

---

lib/plugins/graphite/data-generator.js

The missing newline after last metric was causing the last metric in every section to not make it to graphite.

Missing newline caused last metrics to be lost when sent to graphite #932

---

CHANGELOG.md
lib/plugins/html/assets/css/sitespeed.css
lib/plugins/html/htmlBuilder.js
lib/plugins/html/index.js
lib/plugins/html/templates/url/index.jade

- always show results from plugins that succeed
- provide some context to the error by including the plugin name
- style errors with beautiful pink background
Test by running:
bin/sitespeed.js http://www.expressen.se -n1 -b chrome --webpagetest.key foo

Show other results even if one plugin has error.

---

CHANGELOG.md
lib/plugins/assets/aggregator.js
lib/plugins/html/templates/assets.pug
lib/support/util.js

Quick hack to add a shortenURL for HTML output for URLs longer than 30 characters for #874. Code should probably be moved to a function and tests needed.

Shrink URL on Asset HTML report for any relatively long URLs

---

CHANGELOG.md
lib/plugins/html/helpers/size.js

Returning N/A if nothing to display to fix issue with text overlap on tablet view of 'Requests and sizes per content type' section of pages and switching to captial unit text to clarify that it is in Bytes.
https://xkcd.com/394/

Empty size fixes for tablet view of pages HTML report

---

lib/plugins/html/templates/url/index.pug
lib/plugins/html/templates/url/run.pug

@soulgalore may be a good idea before 1.0 we split some of these(menu, screenshot, page summary, etc) out into partials that we can include to avoid duplication of HTML and keep things consistent. Not too important though but would be an easy ticket for someone that wants to contribute to pick up.

Sync'ing up menu text on page summary and run summary

---

package.json

Slimerjs package will download slimerjs on installation. This caused too much load on the server and the author has blocked downloads from aws: https://groups.google.com/forum/#!topic/slimerjs/nIi0ZqSNzBs. This was fixed in the slimerjs npm package by using github as a mirror: graingert/slimerjs@63a8288. This PR will use the latest slimerjs version to avoid issues running sitespeedio on aws.

Upgrade slimerjs to avoid issue with download mirror

---

lib/plugins/html/htmlBuilder.js
lib/plugins/html/templates/header.pug
lib/plugins/html/templates/layout.pug
lib/plugins/html/templates/pages.pug
lib/plugins/html/templates/url/coach/index.pug
lib/sitespeed.js
lib/support/storageManager.js
test/storageManagerTests.js

- rename relativePathFromUrl to pathFromRootToPageDir to make it more obvious what it does.
- join relative url path with / instead of using the path module (should make paths work on all OSes).
- remove path parameter for url run pages, since it wasn't used.
- make StorageManager constructor signature follow node conventions (options last) and add some StorageManager tests.

Correct way of creating relative urls in html site

---

lib/plugins/browsertime/aggregator.js
lib/plugins/browsertime/analyzer.js
lib/plugins/browsertime/index.js
lib/plugins/html/setup/detailed.js
lib/plugins/html/setup/summaryBoxes.js
lib/plugins/html/templates/url/browsertime/index.pug
lib/support/cli.js

Made the simplest solution for adding your own script. 
Use <code>--browsertime.script myScript.js</code> to add your script. You can run multiple script by passing the parameter multiple times.
The metrics will automatically turn up on the summary page, detailed page, the summary page of the page and the run page. They will also be sent to Graphite.
We lack support for passing a dir with multiple files (as we have in Browsertime) but I think it's ok to wait with that!

Run custom scripts

---

lib/plugins/browsertime/index.js
lib/plugins/coach/index.js
lib/plugins/crawler/index.js
lib/plugins/gpsi/index.js
lib/plugins/webpagetest/index.js
lib/support/url-source.js

Lay the foundation for grouping data from multiple urls. Tag all messages originating from a single url (browsertime.pageSummary, coach.pageSummary etc.) with a group. Aggregations based on group will be a breaking change, so that will follow in a later changeset.
Urls passed directly on the command line will be tagged with a group based on the domain. When passing urls via text files, the group will be generated from the file name.

Tag messages with group, based on url or filename.

---

lib/plugins/html/renderer.js

Fixes #1219 and #1218.
There is no clear benefit in rendering async as each process is roughly of equal time -- so I don't think we losing anything going sync -- and gaining much better memory management.

Process pug synchronously for better memory management - fixes #1219

---

CHANGELOG.md
lib/plugins/assets/index.js
lib/plugins/datacollector/index.js
lib/plugins/metrics/index.js

The old structure was made in a hurry and only usable for HTML output. The new structure opens up so we can send the toplist to Graphite or use in a budget. You can now graph the largest size for an asset content type or make budget that's breaks if we have one image larger than X.

Change toplist data structure

---

lib/plugins/slack/index.js

Since the default channel has been removed we cannot directly check if the channel starts with `#`, we'll need to make sure that the channel is defined before.
#1234

Should only check the slack channel prefix if the channel is defined.

---

lib/plugins/html/templates/url/browsertime/index.pug
lib/plugins/html/templates/url/tabs.pug
lib/plugins/html/templates/url/waterfall/index.pug

The rootPath ends with a trailing slash and adding an extra slash in the pugs will create an invalid url for some web servers e.g. S3
There's a unit test that asserts that the rootUrl should end with a slash and I'm assuming that it's correct. I've removed the appending slash from the locations that I can find.

Remove additional slash to rootPath in pugs

---

Dockerfile
docker/scripts/start.sh

Been following http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html  to not run as root inside the container.  I've seen when I run on Ubuntu not as root, that the owner of the files in sitespeed-result is ... root!  I've tested this locally on my Mac but not on Ubuntu, could you try it out @beenanner ?

Don't run as root inside Docker

---

CHANGELOG.md

This way it will not break automatic parsers like https://allmychanges.com/p/javascript/sitespeed.io/

Fix header level for 4.0.0 release

---

docs/documentation/sitespeed.io/continuous-integration/index.md

Fix a small typo in documentation for continuous integration. Currently the link points to `https://www.sitespeed.io/documentation/sitespeed.io/continuous-integration/(/documentation/sitespeed.io/performance-budget/)`
I'm not sure if the relative path is preferred but i saw this in other places so trying to stick to that.
_Thank you for building an amazing tool!_

Fix link in CI section

---

lib/plugins/assets/aggregator.js
lib/plugins/assets/assetsBySize.js
lib/plugins/assets/index.js
lib/plugins/datacollector/index.js
lib/plugins/graphite/data-generator.js
lib/plugins/html/templates/assets.pug
lib/plugins/metrics/index.js
lib/support/flattenMessage.js

The toplist handling was quite broken in 4.0.0, you couldn't send the metrics to Graphite. With this PR you can + we have a new naming for the toplist, following the standard of summary/pageSummary and we also now has the ability to get the URL for the slowest assets.

Possibility to send asset toplists to Graphite

---

docs/_includes/index/box3.md

The Coach-href on the startpage was misspelled. It links to /documentaion/coach/ instead of /documentation/coach/

Fix spelling error in The Coach link

---

lib/support/messageMaker.js
package.json

Hi there,
This week a new version of the [uuid](https://github.com/kelektiv/node-uuid) module got released. The old module which was available by the name [node-uuid](https://www.npmjs.com/package/node-uuid) got deprecated and will show error message upon every install of the module.
To get rid of those install errors I've created this **automated pull request**. I've run some checks against your code base to test whether you're using one of the [deprecated apis](https://github.com/kelektiv/node-uuid/commit/5ae7287fc935eb55ef39133e4be17ef623ca000e), but this isn't the case.
Please test the changes against your code. I didn't run any tests and therefore can't guarantee that it isn't breaking. You can also just close this pr if you don't want to update your module.
In case there's already …

Update uuid to version 3.0.0

---

lib/plugins/html/templates/url/index.pug
lib/plugins/html/templates/url/webpagetest/index.pug

#Minor bug fixes for webpagetest table mixin and making sure browsertime is enabled before using it in the html output. Fixes #1398 
Tested with: `bin/sitespeed.js https://www.sitespeed.io/ -n 1 --plugins.disable browsertime  <insert all the private webpagetest options>`

Fixing issue with disabling browsertime plugin #1398

---

README.md

the --shm-size option was added with docker 1.10. mention the min docker version in the readme.
see https://github.com/docker/docker/pull/16168

usage of --shm-size requires at least docker 1.10

---

lib/plugins/s3/index.js

This is so a user can take advantage of CredentialProviderChain as mentioned in #1349
Example:
```
export AWS_ACCESS_KEY_ID=xxxxx
export AWS_SECRET_ACCESS_KEY=xxxx
bin/sitespeed.js -n 1 --s3.bucketname somebucket https://www.sitespeed.io
```

Making key and secret optional parameters

---

lib/plugins/budget/index.js
lib/plugins/budget/verify.js
lib/support/cli.js
package.json

I've updates the yargs (cli options library) to version 6.
We reverted this update in #1399 because if caused a conflict between the --budget and --budget.output flags (was automagically fixed in 5 but not anymore in 6).
Using the new version seemed logical for #1431 and because we don't want to be pinned down on an old version of yargs.

Allow budget to be specified inline on cli.

---

lib/plugins/graphite/util.js
lib/plugins/html/htmlBuilder.js
lib/plugins/html/templates/pages.pug

Fixes #1444. Simple script to reproduce issue and verify fix. @soulgalore where should we keep this to run in travis? 
```
const sitespeed = require('../lib/sitespeed');
const urls = ['https://www.sitespeed.io/'];
function run() {
sitespeed.run({ urls })
.then((results) => {
if (results.error) {
throw new Error(results.error);
}
})
.catch((err) => {
console.error(err);
process.exit(1);
});
}
run();
```

Fix for Template error with meta data aliases when not using the CLI #1444

---

lib/plugins/s3/index.js
package.json

* Avoid hang if fs.remove fails.
* Use defaults from s3 module for maxAsyncS3, s3RetryCount etc.
* Always set whichever of region, accessKeyId and secretAccessKey that are passed as options. That allows for an arbitrary mix of options and env. variables.
* Allow configuration of  S3 (such as s3RetryDelay) even when credentials aren’t passed as options.
* Use verbose logging instead of trace (since trace prints a stack trace).

Minor cleanup and tweaks to S3 plugin.

---

lib/plugins/html/templates/url/index.pug
lib/plugins/html/templates/url/run.pug

Removed broken image when screenshot plugin is disabled, aka `--plugins.disable screenshot`
Related to #1570

Don't try to display unexistant screenshot

---

development/index.md
docs/documentation/sitespeed.io/performance-dashboard/index.md

If we close and remove the docker containers use for performance dashboard the data will be kept.
So on the next run it will persists with the new containers. To start from scratch we need to remove the volumes also.
This fixes #1589

Update docs with docker details to remove data volumes

---

docs/documentation/browsertime/index.md
docs/documentation/sitespeed.io/browsers/index.md

Reverts sitespeedio/sitespeed.io#1608
The thing is the download speed is not affected using TC that is what I am trying to explain. Please use  Docker networks.

Revert "Updated connectivity docs for TC to better explain what it will actually happen"

---

lib/support/flattenMessage.js

Fixes #1647 
If the URL key doesn't exist due to customized filtering use the index instead when sending out to TSDBs

Fixes #1647 where URL key doesn't exist due to filter setting

---

lib/plugins/browsertime/index.js

We want to include more meta data of the run in the HAR to make it easier to show extra info when we compare HARs.
This adds the possibility to: show screenshots, video, visualMetrics, link back to the result page  and know about the connectivity. 
This will be used when we compare multiple HAR files.
This should be mergeable asap, we can include it now and start use it in 6.0.

More meta data for the HAR

---

lib/plugins/webpagetest/analyzer.js

Log on warning level instead of error level for issues retrieving data from WPT. It’s not an error in sitespeed, so error is to severe. Additionally make the logging more useful by:
* not adding a stack trace to each log statement
* including the page url for each log statement
* fix some spelling errors in logging.

More useful logging for WPT issues.

---

lib/plugins/browsertime/index.js
lib/plugins/coach/index.js
lib/plugins/screenshot/index.js
lib/sitespeed.js
package.json

Push knowledge about config dependencies between plugins out to the plugins themselves. This reduces centralized knowledge.
This is not a way to specify dependencies on plugins that have to be loaded. We’ll see when (and if) we’ll tackle that.

Pass additional BT config from plugins via message

---

lib/plugins/html/templates/url/tabs/summaryTabs.pug

A faulty indentation put plugin tabs outside the tabs div.
Fixes #1801

Put plugins tabs on correct row.

---

lib/plugins/webpagetest/aggregator.js
lib/plugins/webpagetest/analyzer.js
lib/plugins/webpagetest/index.js
test/webpagetestTests.js

Let the WPT plugin be an example for plugin developers so more or less can copy/paste some code (fixing requires for sitespeed.io code).

Make the WebPageTest plugin independent on sitespeed.io requires

---

CHANGELOG.md
docs/documentation/sitespeed.io/upgrade/index.md

- ~I'm making a big change or adding functionality so I've already opened an issue proposing the change to other contributors, so I got feedback on the idea before took the time to write precious code~
- ~Check that your change/fix has corresponding unit tests (if applicable)~
Since v5.x documentation publicly pointed to the StorageManager API for plugin developers to use, breaking changes in it should probably be documented. (It certainly threw me for a loop when upgrading today!)
I added a brief list of what method signatures changed between 5.x and 6.0.0 to both the changelog and the upgrade guide. Let me know if there’s anything not correct here.

Document breaking StorageManager changes in v6.0.0

---

.travis.yml

Forks don’t have access to encrypted environment variables on Travis, so referensing $WPTKEY doesn’t work. Instead just run these tests in the sitespeedio/sitespeed.io repo.

Don’t test WPT on Travis for PRs from forks.

---

lib/plugins/browsertime/index.js
lib/plugins/coach/index.js
lib/plugins/screenshot/index.js
lib/plugins/webpagetest/index.js

Add message in the queue that Browsertime and WebPageTest are
read for getting configuration messages. This will make it possible
for other plugins to know if Browsertime or/and WebPageTest is
running.

Notify plugins that Browsertime and WebPageTest will run

---

lib/plugins/webpagetest/pug/index.pug

Fixes #1879 
I think the structure has changed or I implemented it wrong from the beginning :|

Fixed new structure for Chrome user timings

---

lib/plugins/webpagetest/analyzer.js

As mentioned on slack this morning to Peter had a wpt run returning:
```
"fvonly": false,
"successfulFVRuns": 0,
"successfulRVRuns": 0,
....
"median": []
```
as the test location specified was valid, as i got no api request failure but invalid, http://52.208.139.70/results.php?test=180312_HX_40edf20ba14266c6d4d33a03c83164ef
and as we are not checking if the property firstView exists in the median block an undefined error is throw and not catched.
ERROR: [sitespeedio.plugin.webpagetest] Error creating WebPageTest result  TypeError: Cannot use 'in' operator to search for 'chromeUserTiming' in undefined
at /usr/src/app/lib/plugins/webpagetest/analyzer.js:43:28

quick-fix for case of no-succesful wpt runs, undefined error not handled

---

lib/cli/cli.js

PR to make outputFolder as `string` type.  Issues are thrown from the container if the outputfolder is named in a numeric form.
```
docker run -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io --outputFolder "1234" https://www.sitespeed.io/ -n 1
Google Chrome 63.0.3239.132 
Mozilla Firefox 54.0.1
TypeError: Path must be a string. Received 1234
at assertPath (path.js:28:11)
at Object.basename (path.js:1390:5)
at module.exports (/usr/src/app/lib/core/resultsStorage/index.js:25:33)
at Object.run (/usr/src/app/lib/sitespeed.js:52:44)
at Object.<anonymous> (/usr/src/app/bin/sitespeed.js:30:4)
at Module._compile (module.js:643:30)
at Object.Module._extensions..js (module.js:654:10)
at Module.load (module.js:556:32)
at tryModuleLoad (module.js:499:12)
at Function.Module._load (module.js:491:3) …
```

make outputFolder as string type

---

docs/documentation/sitespeed.io/configuration/config.md
lib/cli/cli.js
lib/plugins/graphite/data-generator.js
lib/plugins/graphite/graphite-sender.js
lib/plugins/graphite/helpers/format-entry.js
lib/plugins/graphite/helpers/is-statsd.js
lib/plugins/graphite/index.js
lib/plugins/graphite/sender.js
lib/plugins/graphite/statsd-sender.js
test/graphiteTests.js

I'm optimistic about the comment in issue #777:
> ❝  If we want StatsD to work we need PR that makes it configurable. ❞
Send graphite data via StatsD, Lintening on UDP connections (DGRAM) via `graphite.statsd` [boolean]
Avoid `EMSGSIZE` errors from services limiting data size (like default StatsD) by setting a `graphite.bulkSize` [?number]
I have created a graphite sender superclass, supporting bulkSize feature on both default Graphite sender and the new StatsD sender.
The plugin's index (select sender) and data generator (determine format) use an explicit check (`helpers/is-statsd` module), `graphite.statsd` option must equal exactly to `true`.
| Existing settings (no statsd and no bulk) | Setting statsd to true and bulkSize to 20
| --- | ---
| …

Add StatsD support (with bulking)

---

lib/plugins/graphite/helpers/format-entry.js
test/graphiteTests.js

My implementation was error
StatsD supports the types:
* counter `c` (default)
* timer `ms`
* set `s`
* gauge `g`
* histogram `h`
So `t` defaulted to counter

FIX statsd timer

---

docs/documentation/sitespeed.io/configuration/index.md

Replace tabs with spaces in the example for the configuration as JSON

Fix tab spacing for configuration as JSON example

---

lib/plugins/graphite/data-generator.js
test/graphiteTests.js

Addressing issue https://github.com/sitespeedio/sitespeed.io/issues/2106 : StatsD formatting with excess of timestamp at end of line
```
sitespeed_io.default.pageSummary.hey_car._.chrome.3gfast.browsertime.statistics.cpu.events.XHRReadyStateChange.p90:1|ms 1532331394
```
Some implementations of StatsD will allow this excess while other do noe. None of them use it.
`util`'s string formatter places any "extra" arguments at the end of the string - and this is why this string was included while not needed by the format.
I have changed the number of arguments to exclude this string from every line. This should fix the issue

[FIX] StatsD entry format

---

lib/core/resultsStorage/resultUrls.js
lib/plugins/browsertime/index.js
lib/plugins/graphite/index.js
lib/plugins/influxdb/index.js
lib/plugins/slack/attachements.js

This is not perfect but I think it could be the first step. We need to link directly to /index.html instead of just / so that we can use Digital Ocean and others who don't support / solving to index.html.

Use path so we in the future can add full URL including index.html

---

bin/browsertimeWebPageReplay.js

There was bug that made testing multiple pages break when caching
them in the record state.

Fix testing multiple pages in a row with WebPageReplay

---

lib/plugins/browsertime/index.js
lib/plugins/pagexray/index.js

This works fine with the current WebPageTest, GPSI and Lighthouse.
https://github.com/sitespeedio/sitespeed.io/issues/2260

By default use the supplied URL instead of final URL

---

lib/plugins/html/templates/url/metrics/cpu.pug

This will not fix the original problem but at least make sure
we don't fail. #2310

Extra guard for missing CPU data

---

lib/plugins/browsertime/default/metricsPageSummary.js

Send timeToContentfulPaint and timeToFirstInteractive by default to Graphite/InfluxDB

---

lib/cli/cli.js
lib/plugins/html/templates/runInfo.pug
lib/plugins/html/templates/url/includes/pageRunInfo.pug

Browsertime supports `connectivity.alias` option to give connectivity profiles a custom name, though this is not documented in the Sitespeed cli help, and not consistently used in Sitespeed. (only used for writing to DB, but not in reports)
This PR
- adds option to sitespeed cli
- uses the alias in html reports
- adds documentation
Cheers,
Ferdinand

Improve use of browsertime.connectivity.alias option

---

lib/plugins/html/templates/url/thirdparty/index.pug
lib/plugins/thirdparty/index.js

This makes it easier to contribute to third party web +
makes it possible for us to track unmatched domains (even though
we don't do that at the moment).

List unmatched third party domains.

---

lib/plugins/html/templates/pages.pug

We need this if you try to catch a URL that don't work.

catch missing pagexray

---

docs/documentation/sitespeed.io/mobile-phones/index.md
docs/documentation/sitespeed.io/thirdparty/index.md
lib/cli/cli.js

To follow the same setup as Browsertime.

Use --android to test Chrome stable on Android

---

lib/plugins/pagexray/index.js
lib/plugins/thirdparty/index.js

When you tested URLs on different domains in the same script.

Bugfix: PageXray and the third party plugin sent messages in wrong group

---

lib/plugins/budget/friendlynames.js
lib/plugins/budget/verify.js
lib/plugins/pagexray/index.js
test/budget.json

on budget verify, check for responseCode from
pagexray message body and log any status code > 399
2318

feat -verify http status in budget (and log errors)

---

lib/plugins/graphite/data-generator.js

Rename user timings and assets when running in perIteration mode. Fixes #2693
It is as late as we can rename the metrics while also knowing that we are running a per-iteration mode. It is right before it is sent out and should have no impact on anything downstream since it just rewrites the key instead of the object used for analysis.

fix(graphite): update indexed keys with names

---

Dockerfile
docker/scripts/start.sh

-  [ ] I'm making a big change or adding functionality so I've already opened an issue proposing the change to other contributors, so I got feedback on the idea before took the time to write precious code (*This is not a big change IMO*) 
-  [ ] Check that your change/fix has corresponding unit tests (if applicable) (*Not applicable*) 
This updates the start.sh script to create a group and user with the same GID and UID as the working directory (normally /sitespeed.io), then use that for running `node`. This fixes the issue of report files being owned by root reported in https://github.com/sitespeedio/sitespeed.io/issues/1459
This uses "chroot" to switch the new user instead of "su" because of the signal …

Don't run node as root in Docker, fixes #1459

---

docs/_includes/css/sitespeed.css

Hello,
The `h1,h2,h3...` tags vary in size very slightly, which makes understanding the content hierarchy/structure in documentation pages very hard. Here's a **WIP** merge request, I only tested h2 and h3 font-size in the browser dev-tools, even if this PR changes all of them (from h2 to h6). I didn't test locally at all. If someone wants to validate/adjust the changes, it would be awesome for docs readability (and my first contribution to sitespeed :) ).
> Thank you for making sitespeed.io even better!
You're welcome

Better differentiate sizes of HTML title tags

---

docs/documentation/sitespeed.io/scripting/index.md

This example combines the use of commands.js.run and commands.measure.add to show how to add a custom metric from a traditional blog post with the comments count

add extra example under "Add your own metrics"

---

lib/cli/cli.js

And we don't add too much over head.

Disable --cpu for Firefox so we can investigate if all configs are right

---

lib/cli/cli.js
lib/plugins/influxdb/cli.js
lib/plugins/influxdb/index.js
test/cliTests.js

Move `influxdb` plugin CLI options into the plugin defintion/structure.
---
It follows the same pattern implemented for both Graphite/Grafana

feat(plugins): move influxdb CLI options to the plugin defintion

---

lib/plugins/browsertime/index.js
lib/plugins/influxdb/index.js
lib/plugins/influxdb/send-annotation.js

When sending annotations to InfluxDB: instead of using a timestamp
of when the annotation is sent, use when the first run for that
URL was done in Browsertime.

Use Browsertime test time for annotations to InfluxDB #2998

---

lib/plugins/gcs/index.js
lib/plugins/s3/index.js

This makes it possible for other plugins to know if S3 or GCS is configured.

Send a setup message when the plugin start.

---

lib/plugins/html/templates/pages.pug
lib/plugins/html/templates/url/metrics/index.pug

- Not a big change IMO
- I can't find any tests for the HTML plugin
- N/A
- Note: I get 4 test failures for the `test/slackTests.js`, but they fail on the "main" branch too, so it's not related to my change
The `browsertime.chrome.visualMetricsUsingTrace` option is a great way of speeding up test runs, but it causes some problems with the HTML report. For example, the "pages.pug" template won't show table headers for the visual metrics gathered, yet they're present in the table rows, causing a mismatch between the header and rows. Example:
The above screenshot was generated by running `/bin/sitespeed.js  --cpu --browsertime.chrome.visualMetricsUsingTrace --browsertime.chrome.enableTraceScreenshots …

Fix HTML plugin when using "browsertime.chrome.visualMetricsUsingTrace"

---

lib/core/queueHandler.js
lib/plugins/analysisstorer/index.js
lib/plugins/budget/index.js
lib/plugins/html/dataCollector.js
lib/plugins/html/htmlBuilder.js
lib/plugins/html/index.js

One long term "bug/feature" has been that the budget message was passed late
(in the render phase). By adding a phase "prepareToRender", we can pass on
te budget message in that phase and the HTML plugin can use that message instead
of the old "context" hack. This also opens up for some really cool features
coming soon :)

Add prepareToRender message that fixes the timing of the budget message.

---

lib/plugins/browsertime/filmstrip.js

Filmstrips are only stored to disk if we collect visual metrics using trace

---

docker/docker-compose.yml
lib/cli/cli.js
lib/core/resultsStorage/index.js
lib/core/resultsStorage/pathToFolder.js
lib/core/resultsStorage/resultUrls.js
lib/core/resultsStorage/storageManager.js
lib/plugins/graphite/data-generator.js
lib/plugins/influxdb/data-generator.js
test/influxdbTests.js
test/pathToFolderTests.js
test/resultUrlTests.js
test/slackTests.js

You can now give your test a slug. At the moment that is used for the new experimental setup that floors the date to the nearest ten minute slot, to make it possible to go direct from Graphite to data storage.

Introducing slug for your test and a new experimental setup

---

lib/cli/cli.js

I've made a mistake in the stable release and didn't add the
right alias to Browsertime when you run sitspeed.io.
https://github.com/sitespeedio/sitespeed.io/issues/3226

Make sure cli-alias is propagated to Browsertime.

---

lib/plugins/lateststorer/index.js

Make sure names do not collide for different browsers and connectivity.

Include browser and connectivity name

---

lib/plugins/browsertime/default/metricsPageSummary.js
lib/plugins/html/templates/url/summary/index.pug

https://github.com/sitespeedio/sitespeed.io/issues/3262

Show "marked as failure" messages from Browsertime.

---

lib/plugins/html/templates/url/includes/tabScripts.js
lib/plugins/html/templates/url/iteration/index.pug
lib/plugins/html/templates/url/summary/index.pug

#2758 stated the issue of resetting the tab upon page change. This pull request adds a proxy over the navigation links and specifies new page to open with proper tab.

#2758 - fix: keep selected tab open across runs

---

lib/cli/cli.js

That option already exists but it was hidden in sitespeed.io.

Add cli for keeping the original video.

---

lib/plugins/influxdb/data-generator.js

As reported in https://github.com/sitespeedio/sitespeed.io/issues/3415#issuecomment-886460545 the current setup is pretty unusable with data from GSPI and sending them to influx db.
This PR add tags like this:
```
performance,testType=score,category=default,origin=gpsi,summaryType=pageSummary,strategy=desktop,page=_,group=www_wikipedia_org,testName=www_wikipedia_org time=1627484589258,value=100
seo,testType=score,category=default,origin=gpsi,summaryType=pageSummary,strategy=desktop,page=_,group=www_wikipedia_org,testName=www_wikipedia_org time=1627484589258,value=0
accessibility,testType=score,category=default,origin=gpsi,summaryType=pageSummary,strategy=desktop,page=_,group=www_wikipedia_org,testName=www_wikipedia_org time=1627484589258,value=0 …
```

Add better tags to InfluxDB for GPSI data.

---

lib/plugins/html/htmlBuilder.js
lib/plugins/html/templates/url/summary/index.pug
lib/plugins/html/templates/url/summary/metrics/index.pug
lib/support/friendlynames.js
lib/support/helpers/decimals.js
lib/support/helpers/httpErrors.js
lib/support/helpers/index.js

Adds a new page that show metrics (that exists as friendly names) side by side for all runs. Helpful to use to see the spread of the metrics.

Metrics per run side by side

---

lib/cli/cli.js
lib/plugins/crawler/index.js

For example we have an internal test site (a sort of showcase of all our modules), that has a noFollow rule on all its pages. With that the crawler refuses to discover any pages. However there is an option in the crawler to ignore the robots.txt. This is basically my attempt at passing that option through. I have this currently running as a patched version on our site.

Add option for crawler to ignore robots.txt

---

README.md

Removed "$" from project setup commands as it is already there in the terminals ,hence creates a mess when we directly copy pastes the commands
Not a big issue

removed "$"

---

lib/plugins/budget/verify.js
lib/plugins/html/htmlBuilder.js
lib/plugins/html/templates/budget.pug

One thing that do not work 100% correct is if we have multiple URLs
with the same alias, then it could be that we do not show the correct
URL in the budget HTML file.
https://github.com/sitespeedio/sitespeed.io/issues/3570

Show alias in result budget json.

---

lib/plugins/html/metricHelper.js

See https://github.com/sitespeedio/sitespeed.io/issues/3618

Make sure visual metrics exists for a run before it is used

---

lib/plugins/html/templates/url/thirdparty/index.pug

This catches if the user use --firstParty but actually
do not match any requests.
https://github.com/sitespeedio/sitespeed.io/issues/3642

Check if the user uses --firstParty.

---

lib/plugins/html/htmlBuilder.js

This fixes a minor typo in `HTMLBuilder` that prevents plugins from adding custom CSS to the rendered HTML output.

plugins/html: Fix typo with inline CSS handling

---

docker/docker-compose.yml
lib/cli/cli.js
lib/plugins/browsertime/default/metricsRun.js
lib/plugins/browsertime/default/metricsRunLimited.js
lib/plugins/browsertime/index.js
lib/plugins/coach/index.js
lib/plugins/graphite/cli.js
lib/plugins/graphite/data-generator.js
lib/plugins/graphite/index.js
lib/plugins/pagexray/index.js
lib/plugins/thirdparty/index.js
lib/support/flattenMessage.js

**Breaking** but **better** changes coming up:
Sending metrics per run to Graphite:
* The default setup did miss a lot of important performance metrics, so you needed to set them up yourself. That is fixed in this PR.
* There where a lot of data sent from PageXray, third party and the coach per run. That was not smart since those metrics rarely change between runs and take a lot of space. This PR sets default so none of those metrics are sent
* We introduce a limited set of run metrics from Browsertime (visual metrics and Google Web Vitals and a couple of more) that can be used when sending data per run. This will help you keep track of those metrics together with the default median/min/max values. More info coming up. It's enabled by default, disable it with `--browsertime.limitedRunData …

Make it easy to send run data to Graphite in a sane way

---

lib/cli/cli.js

If you as an API user just want to get the result, you don't need a URL.

api: fix text and change guard for not supplying URLs

---

docs/documentation/sitespeed.io/configuration/config.md
lib/cli/cli.js
lib/plugins/graphite/index.js
lib/plugins/graphite/send-annotation.js

Add support to alter the URL path to graphite-web events endpoint when behind a proxy.
Tested with my own instance of graphite-web running behind a proxy.

add proxyPath config for graphite web endpoint

---

.github/workflows/docker.yml
.github/workflows/linux.yml
.github/workflows/safari.yml
.github/workflows/windows.yml
lib/cli/cli.js
test/exampleConfig.json

https://github.com/sitespeedio/sitespeed.io/issues/3920

Fix: read config file on Windows

---

lib/plugins/html/templates/url/metrics/elementTimings.pug

https://github.com/sitespeedio/sitespeed.io/issues/3926

Fix: Element timings without images was shown wrong.

---

lib/plugins/compare/helper.js
lib/plugins/compare/index.js

If the change is not significant, it will be zero. Else Cliffs delta is used to determine how large the change is.
In Graphite we could then alert on everything > 0. And then match Cliffs delta to tell us if the change is small, medium or large.

Add isSignificant to result.

---

bin/sitespeed.js

https://github.com/sitespeedio/sitespeed.io/issues/3667
This makes it possible to set the exit code in your script.

Only set exit code if you haven't set it already.

---

bin/sitespeed.js

I introduced a bug when I added support for exit codes from Browsertime/scripting. This fixed that bug and makes the code simpler to read/understand.
https://github.com/sitespeedio/sitespeed.io/issues/4062

Simplify exit code logic.

---

lib/cli/cli.js

We used to automatically choose throttle as network emulator on Mac and Linux but that was broken when Android functionality was restructured.

Fix broken check for -c cable on Mac/Linux.

---

lib/plugins/compare/index.js

If you don't give your compare an id, this will add browser, connectivity and slug to the filename. This is a breaking change if you use the compare plugin without an id.

Use browser, connectivity and slug in compare name.

---

lib/plugins/browsertime/analyzer.js

This simple PR corrects the logging message for the start of pre-testing/warming. Currently, the output is:
`INFO: Start pre-testing/warminghttps://www.sitespeed.io`
With this fix, the output will be:
`INFO: Start pre-testing/warming https://www.sitespeed.io`

Fix: Add space to pre-testing/warming log

---

lib/cli/cli.js

They already exists in Browsertime.
https://github.com/sitespeedio/sitespeed.io/issues/4189

Add CLI params to turn off LCP/LS screenshots.

---

lib/plugins/html/templates/url/metrics/layoutShift.pug
lib/plugins/html/templates/url/metrics/lcp.pug

On the indivisual run page, it always showed the first image instead of the image from that specific run.
https://github.com/sitespeedio/sitespeed.io/issues/4218

Show correct image for LCP and CLS.

---

lib/plugins/influxdb/send-annotationV2.js

Fix for this changes - https://github.com/sitespeedio/sitespeed.io/commit/94854aad48e8c906bd288d61494b1b637ecff46d
Missed add a key for `slug`

Fix. InfluxDB 2.x, annotations: missed 'slug' key

---

bin/browsertimeWebPageReplay.js

The camel case is evil since it makes some metrics becoming arrays.

WebPageReplay: Deep merge configuration and skip camel case.

---

lib/plugins/html/src/sass/dark/components/chartist.scss
lib/plugins/html/src/sass/light/components/chartist.scss
lib/plugins/html/templates/url/metrics/visualProgress.pug

This PR resolves : [Issue#2761](https://github.com/sitespeedio/sitespeed.io/issues/2761)
Before : 
After :

fix x-axis label collision

---

lib/plugins/compare/index.js

I ran into an error on this line while playing around with the compare plugin, where timestamps is undefined.

Fix error on warning msg

---

lib/cli/cli.js

After this --android will work but will not be showed as an alias. The problem was that we had issues with the android configuration object becoming an array instead of an object.

Fix broken --android parsing.

---

docs/_layouts/default.html
docs/feed/blog.xml

* Point rss discovery to canonical URL.
Update discovery link to the current canonical URL for where the blog RSS feed lives. The redirect is kept for compatibility. This avoids feed readers from becoming unsure about the feed location by not re-crawling and re-fixing the redirect repeatedly.
* Fix 404 from https://www.sitespeed.io/feed/blog.xml to `https://www.sitespeed.io/feed.xml` which may confuse feed readers if they replace their link with the preferred self location, but then lose the subscription to an HTTP 404 error.
* Shorten the feed title and start with "Sitespeed.io" so that it sorts well alongside other blogs in a feed reader under the default suggested name.

blog: Improve RSS feed
