- .travis.yml
there were some spurious line-breaks in the middle of the .travis.yml config file.   This nitpick PR removes them :)
(It seems to get parsed ok, but it's confusing to read for humans).
> removed line-breaks from travis yaml.

- lib/analyze/screenshots.js
@soulgalore I think that this should fix my screenshot problem, which I posted under #691.
I can't test it out right now though because my target environment is a bit messed up at the moment. I'll do that tomorrow.
> All args to the screenshot script should be passed in the right order

- lib/tests/testRenderer.js
Fix for #751.
@soulgalore I tested this locally.
> Add ability to budget on a per rule basis

- lib/tests/testRenderer.js
- templates/budget.hb
@soulgalore this should work, but I'm having trouble testing it right now because for some reason the install of browsertime 0.11.0 is hanging in my environment.
I'll try installing this branch and testing it again tomorrow.
> Do not report skipped rules as failed on the Budget page.

- lib/analyze/screenshots.js
- lib/headless/scripts/screenshot.js
@soulgalore I wasn't sure - do you prefer issues with PRs that fix them, or is just the PR ok?
> Add waitScript logic to screenshots

- lib/analyze/screenshots.js
@daehin this needs to be tested before merging and is in progress. For: https://github.com/sitespeedio/sitespeed.io/issues/791
> WIP: Add ability to use proxy configuration for screenshots

- lib/analyze/screenshots.js
Reverts sitespeedio/sitespeed.io#803
> Revert "WIP: Add ability to use proxy configuration for screenshots"

- lib/plugins/coach/index.js
Adding overall score to defaults so they are sent to graphite.
> Coach total score to graphite

- bin/sitespeed.js
- lib/support/cli.js
Seemed like this would be a good candidate for aliasing as it would most likely be a commonly used option.
> Aliasing crawler depth to '-d' for easy of use.

- lib/support/cli.js
Better examples should be added to the documentation part of the site once we get past the alpha phase, but nice to have here for those that don't read documentation. ;-)
> Adding simple example to help menu for 3rd party vs 1st party metric capturing

- lib/plugins/html/templates/url/coach/index.jade
Only toggle the adjacent element advice for the show/hide button clicked on the detailed HTML page
> Toggle show/hide improvement

- lib/plugins/coach/pagexrayAggregator.js
- lib/plugins/html/templates/index.jade
Adding response codes summary for #923
> Adding responseCodes to summary for graphite

- .travis.yml
One thing missing for us today is that we don't automatically test the WebPageTest code path. Lets do that!
> Add automatic test on WebPageTest in Travis

- bin/sitespeed.js
- lib/sitespeed.js
- lib/support/logging.js
Lets move functionallity from bin inside the application,
making it possible to run without bin.
> Restructure bin functionality to application

- lib/plugins/html/templates/url/pagexray/index.jade
- lib/support/cli.js
Only show 1st vs 3rd summary in HTML output if it has data and show default storage location for HTML ouput in help menu
> Minor tweak to only display 3rd vs 1st module in HTML output if values exist

- HELP.md
Updating help wanted docs. Did this during the call with Peter on The Changelog.
> If it's important put it at the top

- bin/sitespeed.js
- lib/sitespeed.js
- lib/support/cli.js
- package.json
> Disable default plugins (if you want) #1015

- lib/sitespeed.js
- lib/support/cli.js
- lib/support/pluginLoader.js
Super simple version to load your own plugin. 
Check it out @tobli if it something like what you've been thinking about.
> Load plugin

- lib/plugins/html/htmlBuilder.js
- lib/plugins/html/templates/url/index.pug
- lib/plugins/html/templates/url/run.pug
- lib/plugins/html/templates/url/waterfall/index.pug
- lib/support/cli.js
Will make it easier to see the waterfall graph.
> Move waterfall to summary

- CHANGELOG.md
- lib/support/cli.js
- lib/support/storageManager.js
> Passing --outputFolder now works correctly.

- lib/plugins/slack/attachements.js
- lib/plugins/slack/index.js
- lib/plugins/slack/summary.js
- lib/support/cli.js
Pickup specific errors from a URL and slack them #1261 and add to the cli to only slack on errors #1260.
> Slack: Act on error

- docs/documentation/sitespeed.io/docker/index.md
> added docs for VNC server

- lib/plugins/datacollector/index.js
- lib/plugins/domains/aggregator.js
- lib/plugins/domains/index.js
- test/domainTests.js
I've missed to follow the group pattern for domains. Now we have a "total" where we collect everything and individual per base page domain.
Fixes #1290 and part of #1289.
> Group domains

- lib/plugins/browsertime/index.js
> Move mobile config into browsertime, closes #1298

- docs/_includes/header.html
- docs/_posts/2016-10-27-sitespeed.io-4.0-is-released.md
- docs/documentation/sitespeed.io/getting-started/index.md
Fixed some 404 links and a spelling error in the top menu
> Fix more broken urls in docs

- package.json
Upgrading moment to latest. See #1328
> Upgrading moment for 'Regular Expression Denial of Service' reported by snyk #1328

- .github/CONTRIBUTING.md
Steps to Reproduce:
1. Load https://github.com/sitespeedio/sitespeed.io/blob/master/.github/CONTRIBUTING.md
2. Click on "list" (https://github.com/sitespeedio/sitespeed.io/blob/master/.github/HELP.md)
Actual Results:
404, because HELP.md lives not in /.github/, but just off the root directory: https://github.com/sitespeedio/sitespeed.io/blob/master/HELP.md
This works in my local branch, after the fix.
Cheers!
> Fix relative-path link

- package.json
With https://github.com/sitespeedio/sitespeed.io/pull/1344 a deprecated dependency has been replaced, but the old one is still being imported, causing deprecation warnings for no reason.
> Remove unused (deprecated) dependency node-uuid

- lib/plugins/html/templates/url/pagexray/index.pug
- package.json
This adds onto the first vs third party info with a breakdown of content types for each.
> Surface first vs third party content type info 

- docs/_posts/2016-12-13-friendly-url-names.md
> 4.2 coming soon

- lib/plugins/html/templates/pages.pug
- lib/plugins/html/templates/url/index.pug
- lib/support/storageManager.js
This fixes the issue found in #1346. Needs some extra testing. :-)
> Encoding problems urls

- docs/documentation/sitespeed.io/performance-dashboard/index.md
- docs/index.md
- [x ] Update the documentation https://github.com/sitespeedio/sitespeed.io/tree/master/docs
just a broken link fix on the docs start page and edited the dashboard doc since I was also trying to send metrics locally over localhost as mentioned in an old issue -> #680
> small docs update

- grafana-setup/dashboards/siteSummary.json
Sorry, just happened to notice while looking at the dashboard!
* Just fixing a super-minor typo that I happened to notice while perusing the dashboard!
> Fix super-minor typo

- docs/README.md
- docs/documentation/sitespeed.io/developers/index.md
- docs/documentation/sitespeed.io/performance-dashboard/index.md
Some minor documentation updates for sizing docker containers
> Added more docs for memory considerations. Also minor dev doc updates

- docs/documentation/sitespeed.io/plugins/index.md
Before merging I think it's probably worth creating a simple hello-world plugin repo as a way to test that this continues to work as well as it will give a concrete example for users to follow. Thoughts?
> Adding docs around plugins and docker #1440

- lib/support/cli.js
Is there a better way to group the options, check https://github.com/yargs/yargs#groupkeys-groupname
> Added Firefox & Chrome specific options

- lib/plugins/s3/index.js
- lib/support/cli.js
Should fix: https://github.com/sitespeedio/sitespeed.io/issues/1468
> Add S3 region option

- docs/3.x/configuration/index.md
- docs/_posts/2016-10-27-sitespeed.io-4.0-is-released.md
- docs/_posts/2016-12-01-speed-index-and-video.md
- docs/documentation/browsertime/index.md
- docs/documentation/coach/developers/index.md
- docs/documentation/coach/introduction/index.md
- docs/documentation/pagexray/index.md
- docs/documentation/sitespeed.io/configuration/index.md
- docs/documentation/sitespeed.io/metrics/index.md
- docs/documentation/sitespeed.io/performance-dashboard/index.md
- docs/documentation/sitespeed.io/upgrade/index.md
- docs/examples/index.md
- docs/release-notes/3.1/index.md
- docs/release-notes/3.2/index.md
- docs/release-notes/3.5/index.md
- lib/support/cli.js
> Fixed typos

- CONTRIBUTORS.md
> Fixed typo

- lib/plugins/html/templates/pages.pug
> Show SpeedIndex and related metrics if we have it in pages

- lib/plugins/html/templates/url/summaryBox.pug
> First step to link summary box content to the exact run #1457

- lib/plugins/slack/attachements.js
- lib/plugins/slack/index.js
- lib/plugins/slack/summary.js
* Use lodash.get to simplify optional properties
* Sync metric titles for summary and attachments.
> Refactor Slack plugin for readability.

- lib/plugins/html/templates/url/browsertime/index.pug
Then make WebPageTest follow the same pattern with metrics, that will be cool!
> Let us make Browsertime result look good

- lib/plugins/html/htmlBuilder.js
- lib/plugins/html/templates/runInfo.pug
- lib/plugins/slack/index.js
- lib/plugins/slack/summary.js
- lib/plugins/text/index.js
- lib/plugins/text/textBuilder.js
- lib/sitespeed.js
Then we can introduce a way of adding a name in next step?
> Stop using options.urls[0] and start using the name of the run

- lib/plugins/html/htmlBuilder.js
- lib/plugins/html/metricHelper.js
- lib/plugins/html/templates/url/browsertime/index.pug
- lib/plugins/html/templates/url/waterfall/fetchHAR.pug
- lib/plugins/html/templates/url/waterfall/includeHARinHTML.pug
- lib/plugins/html/templates/url/waterfall/index.pug
> Choose medianRun HAR from SpeedIndex or RUMSpeedIndex #1505

- docs/documentation/sitespeed.io/mobile-phones/index.md
> Android video docs

- docs/documentation/sitespeed.io/browsers/index.md
- docs/documentation/sitespeed.io/configuration/index.md
- docs/documentation/sitespeed.io/metrics/index.md
- docs/documentation/sitespeed.io/mobile-phones/index.md
- docs/documentation/sitespeed.io/performance-budget/index.md
- docs/documentation/sitespeed.io/plugins/index.md
- docs/documentation/sitespeed.io/prepostscript/index.md
- docs/documentation/sitespeed.io/upgrade/index.md
- docs/documentation/sitespeed.io/use-cases/index.md
- docs/documentation/sitespeed.io/webpagetest/index.md
> Docker docs update

- docs/documentation/browsertime/index.md
I'm just fixing non-executable Markdown documentation, as I came across a few typos and nits - please take no offense, and thanks -- as always -- for your work on Sitespeed.io!
> Fixes minor typos/nits

- docs/documentation/sitespeed.io/configuration/index.md
Just another round of typo fixes; more coming as I work my way through all the docs!
> Another round of typo fixes

- docs/faq/index.md
Another hopefully cut-and-dry doc-fix PR; r?, @soulgalore
> Minor FAQ cleanup

- lib/plugins/webpagetest/aggregator.js
> Fix for when wpt returns no data and a 200 response - Temp Fixes #1685

- docs/documentation/sitespeed.io/getting-started/index.md
- docs/documentation/sitespeed.io/performance-budget/index.md
- docs/documentation/sitespeed.io/performance-dashboard/index.md
Another round of doc-cleanup-tweaks for you, @soulgalore <3
> Random, minor doc cleanup

- package.json
> Bump pagexray to 1.0.1.

- lib/plugins/budget/index.js
- lib/plugins/html/index.js
- lib/plugins/metrics/index.js
- lib/plugins/s3/index.js
- lib/plugins/slack/index.js
- lib/sitespeed.js
Let us iterate through this a couple of times (and test :)) before we merge. I think we should verify that this works by removing the hooks + in the next step clean up the code in each plugin.
> Remove hooks and use messages instead

- lib/plugins/assets/index.js
- lib/plugins/browsertime/index.js
- lib/plugins/coach/index.js
- lib/plugins/crawler/index.js
- lib/plugins/domains/index.js
- lib/plugins/gpsi/index.js
- lib/plugins/html/index.js
- lib/plugins/s3/index.js
- lib/plugins/webpagetest/index.js
- lib/sitespeed.js
- test/webpagetestTests.js
Feed plugins with messageMaker through context instead of require making it easier for plugin makers to send messages.
> Feed plugins with messageMaker

- lib/plugins/assets/index.js
- lib/plugins/browsertime/index.js
- lib/plugins/coach/index.js
- lib/plugins/domains/index.js
- lib/plugins/gpsi/index.js
- lib/plugins/graphite/index.js
- lib/plugins/influxdb/index.js
- lib/plugins/metrics/index.js
- lib/plugins/webpagetest/index.js
- lib/sitespeed.js
- test/webpagetestTests.js
Let all plugins be feed by filterRegistry instead of require so it's easy for plugin makers.
> Feed plugins with filterRegistry

- lib/plugins/html/htmlBuilder.js
- lib/plugins/html/index.js
- lib/plugins/html/templates/layout.pug
Make it easy to override the CSS for all pages.
> Generic way for plugins to override css

- docs/documentation/sitespeed.io/continuous-integration/index.md
> update configuration parameter of latest version

- lib/plugins/pagexray/index.js
When you run WebPageTest standalone.
> Let WebPageTest HAR files be parsed by PageXray

- docs/documentation/sitespeed.io/introduction/index.md
Stumbled a bit when reading the introduction documentation, think these updates might help.
I think prefixing "It should" instead of "It" makes it easier to read without rephrasing too much. Also updated the last bullet point on what I believe to be the intent.
> Improve introduction readibility

- Dockerfile
- Dockerfile.wpr
- package-lock.json
- package.json
FF with the new HAR exporter adds variance to metrics, it is maybe something strange with Chrome 66 beta (adds time to first paint) and then we need to run old browsertime.
> Rollback FF/Chrome and Browsertime

- lib/cli/cli.js
- lib/plugins/s3/contentType.js
- lib/plugins/s3/index.js
- package-lock.json
- package.json
Skip the old and outdated S3 plugin and use our own instead where you can configure
almost everything for your S3 instance/upload.
> New S3 plugin

- lib/plugins/html/templates/_tableMixins.pug
- lib/plugins/html/templates/url/pagexray/after.pug
- lib/plugins/html/templates/url/pagexray/index.pug
We could do something fancier: showing % etc, but for now, let use
the raw data from latest PageXray and show it.
> Show requests loaded after onLoad.

- docs/documentation/sitespeed.io/configuration/index.md
Update to reflect this change: https://github.com/sitespeedio/sitespeed.io/blob/master/CHANGELOG.md#deprecations
😀
> Update the documentation file

- lib/cli/cli.js
- lib/plugins/grafana/index.js
- lib/plugins/grafana/send-annotation.js
- lib/plugins/graphite/index.js
- lib/plugins/influxdb/index.js
- lib/plugins/influxdb/send-annotation.js
- lib/support/annotationsHelper.js
Let us try this out and aim to release it when Grafana goes 5.4.
> Prepare for using Grafana annotations with tags (coming in Grafana 5.4)

- lib/plugins/browsertime/aggregator.js
- lib/plugins/browsertime/default/metricsPageSummary.js
- lib/plugins/html/setup/detailed.js
Send the to tsdb and show them in detailed view.
> Use paint timings

- lib/plugins/html/templates/url/metrics/index.pug
As a first step we can just show the metrics. Next step show where in the screenshot.
> Show visual elements data

- docs/_includes/footer.html
- docs/_includes/header.html
- docs/_layouts/default.html
- docs/_layouts/startpage.html
> Better HTML for screenreaders

- docs/_headers
Reverts sitespeedio/sitespeed.io#2212
> Revert "docs: add csp"

- docs/_headers
> try out csp

- docs/documentation/sitespeed.io/continuous-integration/index.md
Update continuous integration documentation by adding a section for running sitespeed.io on CircleCI. This PR includes an example config file that shows how to run sitespeed.io docker with the following options
- With traffic shaping
- Without traffic shaping
- With a performance budget file
> docs: add circleci configuration section

- lib/plugins/html/setup/detailed.js
- lib/plugins/html/setup/summaryBoxes.js
- lib/plugins/html/templates/url/iteration/index.pug
- lib/plugins/html/templates/url/metrics/index.pug
- lib/plugins/html/templates/url/pagexray/index.pug
- lib/plugins/html/templates/url/summary/index.pug
- lib/plugins/pagexray/index.js
- lib/plugins/pagexray/pagexrayAggregator.js
We now uses the FUlly Loaded from the HAR and using the one from
Browsertime gives us stats like median, so let us use that!
> Use Fully Loaded from Browsertime instead of PageXray

- docs/documentation/sitespeed.io/performance-dashboard/index.md
> Spelling correction

- docs/documentation/sitespeed.io/scripting/index.md
> Correct 'measure one page after login' scripting example

- lib/cli/cli.js
> Add missing spaces

- docs/documentation/sitespeed.io/scripting/index.md
> Fix spelling error

- docs/documentation/sitespeed.io/scripting/index.md
> typo measuure

- lib/plugins/budget/friendlynames.js
> Add pageLoadTimes #2338

- lib/plugins/influxdb/data-generator.js
There were no audit tag in InfluxDB for lighthouse.pageSummary.audits.*.rawValue, so I added it to make it possible to add multiple audits from one test to InfluxDB (https://github.com/sitespeedio/plugin-lighthouse/issues/11)
> Added Lighthouse audit tag for InfluxDB

- lib/plugins/browsertime/index.js
https://github.com/sitespeedio/sitespeed.io/issues/2341
> Make sure we spread the knowledge of alias asap.

- docs/documentation/sitespeed.io/connectivity/index.md
> Fix typo in connectivity/index.md

- lib/core/resultsStorage/resultUrls.js
> Use hash configuration when when generating full summary path.

- docs/documentation/sitespeed.io/scripting/index.md
> use command to use commands to be consistent with other examples

- lib/cli/cli.js
- lib/plugins/html/templates/url/thirdparty/index.pug
- lib/plugins/thirdparty/index.js
Show third party stats from median run instead of summary
> Third party summary

- lib/plugins/thirdparty/index.js
Reverts sitespeedio/sitespeed.io#2471
> Revert "Only count unmatched requests"

- docs/_posts/2019-05-21-sitespeed.io-9.0.md
https://www.sitespeed.io/sitespeed.io-9.0/#default-config-file
> Fixed a typo in the blog post

- lib/cli/cli.js
> Using extend missed out on configured objects.

- lib/plugins/browsertime/default/metricsPageSummary.js
> Report JS heap size by default #2514

- lib/plugins/webpagetest/analyzer.js
- lib/plugins/webpagetest/index.js
* Log the full URL to the WebPageTest result page per default
* Add more guards if WebPageTest fails
* Make sure we log all errors from WebPageTest
> WebPageTest: Small fixes to better take care of errors in WebPageTest

- docs/_includes/footer.html
- docs/_includes/header.html
- docs/_includes/index/install.md
- docs/_layouts/default.html
- docs/_layouts/startpage.html
> docs: add roles to HTML

- CHANGELOG.md
- Dockerfile
- lib/plugins/html/filmstrip.js
- lib/plugins/html/templates/url/filmstrip/index.pug
- lib/plugins/html/templates/url/metrics/index.pug
- npm-shrinkwrap.json
- package.json
There are a lot of new things coming, but this PR only make
sure everything works.
> Upgrade to Browsertime 6.0.0-alpha.1

- .travis.yml
- lib/cli/cli.js
- lib/plugins/axe/axePostScript.js
- lib/plugins/axe/index.js
- lib/plugins/axe/pug/index.pug
- lib/plugins/browsertime/axeAggregator.js
- lib/plugins/browsertime/default/metricsPageSummary.js
- lib/plugins/browsertime/index.js
- lib/plugins/graphite/data-generator.js
- lib/plugins/influxdb/data-generator.js
- npm-shrinkwrap.json
- package.json
Add support for running axe: `--axe.enable`
> Make it easy to run axe core

- lib/plugins/grafana/index.js
- lib/plugins/grafana/send-annotation.js
- lib/plugins/graphite/index.js
- lib/plugins/graphite/send-annotation.js
- lib/plugins/influxdb/index.js
- lib/plugins/influxdb/send-annotation.js
* Added connectivity and location tag for WebPageTest
* If you test both using WPT and BT, wait for all metrics to arrive before sending the annotation
* Fix link to WebPageTest that before could link to old result
> Add correct annotation tags when using WebPageTest.

- lib/plugins/grafana/index.js
- lib/plugins/grafana/send-annotation.js
- lib/plugins/graphite/index.js
- lib/plugins/graphite/send-annotation.js
- lib/plugins/influxdb/index.js
- lib/plugins/influxdb/send-annotation.js
- lib/support/annotationsHelper.js
https://github.com/sitespeedio/sitespeed.io/issues/2608
> Use HAR file from WPT in annotations when Browsertime is turned off

- lib/plugins/slack/attachements.js
- lib/plugins/slack/summary.js
* use correct connectivity
* Always have a red color when we have an error
* Use median when checking limit values
#2595
> Slack fixes

- lib/cli/cli.js
- lib/plugins/slack/attachements.js
* firstPaint
* visualComplete85
* lastVisualChange
* fullyLoaded
And fixed broken fullyLoaded.
> Added new metrics for slacking:

- docs/documentation/sitespeed.io/browsers/index.md
- docs/documentation/sitespeed.io/introduction/index.md
> fix spelling mistakes in docs

- lib/plugins/webpagetest/analyzer.js
https://github.com/sitespeedio/sitespeed.io/issues/2620
https://github.com/sitespeedio/sitespeed.io/issues/2617
> Check for multi step WPT result and log that it doesn't work

- lib/plugins/gcs/index.js
> Refactor: duplicate function calls in gcs

- lib/core/resultsStorage/resultUrls.js
> Refactor: duplicate code in resultUrls

- lib/plugins/browsertime/analyzer.js
> fix/--script only works with single JS file, not with directory

- lib/cli/cli.js
> Fix for resultBaseURL as env variable #2663

- lib/cli/cli.js
- lib/plugins/graphite/data-generator.js
- lib/plugins/graphite/index.js
--graphite.experimental.perIteration
> Move per iteration to experimental flag.

- docs/documentation/sitespeed.io/developers/index.md
> docs(documentation): fix typo in sitespeed.io set-up command

- lib/plugins/html/index.js
- package.json
fixes recursive overwriting of user given test metric(s) by default test metric configured.
> fix(pkg.json, html parser): restrict user given param

- docs/documentation/sitespeed.io/performance-dashboard/index.md
> Fix typo and link to "Continuously run your tests"

- docs/_includes/css/sitespeed.css
I tried to scale the headings size better between 3rem and 1.1rem. I tried on a doc page that had headings from h1 to h4 and it looked better than my first MR #2728.
> Thank you for making sitespeed.io even better!
You're welcome.
> Update headings part 2 (part 1 in #2728)

- lib/cli/cli.js
- lib/plugins/crawler/index.js
fixes [#2748](https://github.com/sitespeedio/sitespeed.io/issues/2748)
> Add --crawler.include #2748

- lib/plugins/gcs/index.js
- lib/plugins/s3/index.js
The message will be visible in the HTML and makse the exit code an
error. #2769
> Post error message in the queue if upload fails.

- lib/cli/cli.js
> Add new complete check params from BT

- docs/documentation/sitespeed.io/scripting/index.md
> docs: Updates for 11.5

- lib/plugins/budget/verify.js
- lib/support/friendlynames.js
The bug was introduced with the budget of counting number of
HTTP errors. #2818
> Fix content size bug.

- lib/plugins/browsertime/index.js
fix(index.js in browsertime plugin): add in axe checks and rules to o…
ISSUES CLOSED: #2854
> (fix): Add Axe Filters

- lib/cli/cli.js
- lib/plugins/sustainable/index.js
Lets keep the disable option until we have the local database option.
> Make it possible to disable the hosting check

- lib/plugins/sustainable/pug/index.pug
> Calculate percentage per page view instead of total

- docs/documentation/sitespeed.io/scripting/index.md
Some code examples were missing awaits, so the code would not work because the Promise would not be resolved in time.
> Add missing awaits to code examples

- lib/cli/cli.js
- lib/plugins/graphite/cli.js
- lib/plugins/graphite/index.js
- test/cliTests.js
This is a follow-up from #2984 - now focused on Graphite CLI options.
> Move graphite cli options to plugin

- lib/plugins/html/htmlBuilder.js
- lib/plugins/html/templates/pages.pug
https://github.com/sitespeedio/sitespeed.io/issues/2976#issuecomment-628568308
> Fix showing alias in the HTML

- docs/documentation/sitespeed.io/continuous-integration/index.md
documentation update of GitHub Actions integration; fixes #3016
> update GitHub Actions integration documentation

- docs/documentation/sitespeed.io/continuous-integration/index.md
fix typos in documentation #3016
> fix typos/grammar in documentation

- lib/plugins/browsertime/index.js
- lib/plugins/html/templates/url/iteration/index.pug
- lib/plugins/html/templates/url/iteration/tabs.pug
- lib/plugins/html/templates/url/screenshots/index.pug
- lib/plugins/html/templates/url/summary/index.pug
- npm-shrinkwrap.json
- package.json
And upgrading to Browsertime that support that.
> Show all screenshots for a run in a tab

- npm-shrinkwrap.json
- package.json
> Update to aws 2.701.0

- lib/core/resultsStorage/index.js
- lib/core/resultsStorage/storageManager.js
- lib/sitespeed.js
- test/resultUrlTests.js
- test/storageManagerTests.js
Make sure storage get hold of the options object to make it easier in the future to make storage configurable.
> Use options for storage

- docs/documentation/sitespeed.io/introduction/index.md
> Updated the index.md with some grammatical changes

- npm-shrinkwrap.json
- package.json
google-cloud/storage, aws-sdk, dayjs, uuid and yargs.
> Update minor versions of dependencies.

- docs/documentation/throttle/index.md
Very simple update to the documentation to list all profiles available.
> Add full list of profiles to the docs

- docs/documentation/sitespeed.io/installation/index.md
Adjust link to Sindre Sorhus guide repository
> Adjust link to Sindre Sorhus guide

- lib/plugins/browsertime/index.js
- lib/plugins/slack/attachements.js
As reported in https://github.com/sitespeedio/compare/issues/108
> Fix broken link to screenshots in meta data and Slack.

- lib/plugins/browsertime/index.js
This helps with problem when running on an Android phone and the phone isn't connected to the computer.
Next step would to make sure Browsertime generates a result json with the error, but that can happen later on.
> Catch errors from Browsertime so errors are thrown on the queue.

- docs/documentation/sitespeed.io/configure-metrics/index.md
- docs/examples/index.md
- lib/plugins/browsertime/aggregator.js
- lib/plugins/browsertime/default/metricsPageSummary.js
- lib/plugins/browsertime/default/metricsSummary.js
- lib/plugins/html/metricHelper.js
- lib/plugins/html/setup/detailed.js
- lib/plugins/html/templates/help.pug
- lib/plugins/html/templates/url/metrics/index.pug
- lib/plugins/html/templates/url/summary/summaryBox.pug
- lib/plugins/influxdb/data-generator.js
- lib/plugins/slack/attachements.js
- lib/plugins/text/textBuilder.js
- npm-shrinkwrap.json
- package.json
- test/fixtures/coach.run-0.json
We need also to fix the new domain name structure on disk for this to be merged.
> New Browsertime 11 alpha

- lib/core/resultsStorage/index.js
Reverts sitespeedio/sitespeed.io#3207
> Revert "Use epoch"

- lib/core/resultsStorage/pathToFolder.js
- lib/core/resultsStorage/resultUrls.js
- lib/core/resultsStorage/storageManager.js
- lib/plugins/analysisstorer/index.js
- lib/plugins/assets/aggregator.js
- lib/plugins/assets/index.js
- lib/plugins/browsertime/index.js
- lib/plugins/grafana/index.js
- lib/plugins/graphite/index.js
- lib/plugins/harstorer/index.js
- lib/plugins/html/dataCollector.js
- lib/plugins/html/htmlBuilder.js
- lib/plugins/html/index.js
- lib/plugins/html/templates/url/waterfall/index.pug
- lib/plugins/influxdb/index.js
- lib/plugins/matrix/index.js
- lib/plugins/slack/attachements.js
- lib/plugins/slack/dataCollector.js
- lib/plugins/slack/index.js
- lib/plugins/tracestorer/index.js
https://github.com/sitespeedio/sitespeed.io/issues/3221
> Handle alias correctly

- lib/cli/cli.js
- lib/core/resultsStorage/index.js
- lib/plugins/graphite/cli.js
- lib/plugins/graphite/data-generator.js
Also cleanup the old experimental setup.
> Make it possible to add the slug of the test as a key to the namespace.

- lib/core/resultsStorage/index.js
- lib/core/resultsStorage/storageManager.js
- lib/plugins/browsertime/index.js
This makes is possible to get screenshots in Grafana.
> Hack to copy screenshot file to the base dir.

- lib/cli/cli.js
https://github.com/sitespeedio/sitespeed.io/issues/3244
> Populate alias from file to Browsertime.

- lib/plugins/slack/attachements.js
https://github.com/sitespeedio/sitespeed.io/issues/3244
> Fix the result URL using Slack

- lib/plugins/grafana/send-annotation.js
- lib/plugins/graphite/send-annotation.js
- lib/plugins/influxdb/send-annotation.js
https://github.com/sitespeedio/sitespeed.io/issues/3277
> Avoid sending the slug as annotation if the name collide.

- lib/plugins/crux/index.js
https://github.com/sitespeedio/sitespeed.io/issues/3313
> Fixed broken check so each origin is only tested once.

- docs/documentation/sitespeed.io/scripting/index.md
The PR in https://github.com/sitespeedio/browsertime/pull/1533 added several new commands that can be used in browsertime scripts.  This patch updates the documentation to cover these commands.
> Update scripting documentation to cover new commands in scrolling, mouse events, window switches, and navigation.

- docs/documentation/sitespeed.io/axe/index.md
> Fix broken link

- lib/plugins/html/renderer.js
Fixing this will make sure other templates are generated.
> Do not re-throw if a template fails.

- .github/workflows/docker-scan.yml
https://github.com/sitespeedio/sitespeed.io/issues/3456
> Try trivy for scanning the docker image

- lib/core/pluginLoader.js
See https://github.com/sitespeedio/browsertime/issues/1275
> Do not run the Coach on Safari iOS.

- docs/documentation/sitespeed.io/continuous-integration/index.md
> Fix Gitlab link

- .github/workflows/docker-scan.yml
- .github/workflows/docker.yml
- Dockerfile
- docker/scripts/start.sh
- npm-shrinkwrap.json
- package.json
- release.sh
https://github.com/sitespeedio/sitespeed.io/issues/3291
> Build containers for both amd64 and arm64

- lib/plugins/budget/junit.js
https://github.com/sitespeedio/sitespeed.io/issues/3568
> Fix broken junit

- lib/plugins/html/htmlBuilder.js
- lib/plugins/html/templates/budget.pug
https://github.com/sitespeedio/sitespeed.io/issues/3571
> Add alias name on budget page.

- .github/budget.json
- .github/workflows/sitespeed-io-action-example.yml
Add a simple example on how to run a sitespeed.io action
> sitespeed.io action example

- lib/plugins/html/templates/url/summary/metrics/index.pug
Make it easier to get to the run that collected that metric.
> Add link to each run in side by side metric page.

- lib/plugins/budget/junit.js
https://github.com/sitespeedio/sitespeed.io/issues/3617
> Fix JUnit/alias bug.

- lib/plugins/crux/index.js
- lib/plugins/crux/pug/index.pug
- lib/plugins/crux/repackage.js
See https://groups.google.com/a/chromium.org/g/chrome-ux-report-announce/c/v-h5gKkUEE0
> Add INP and TTFB to the CRUX metrics

- lib/plugins/html/templates/url/metrics/index.pug
https://github.com/sitespeedio/sitespeed.io/issues/3649
> Check that Browsertime got CLS metrics before we try to render.

- lib/cli/util.js
Make it possible to get alias and groupAlias from a text file.
> Get groupAlias from file

- lib/plugins/lateststorer/index.js
https://github.com/sitespeedio/sitespeed.io/issues/3659
> Hack to add Graphite namespace to the file name of latest tests

- docs/documentation/sitespeed.io/scripting/index.md
documentation regarding https://github.com/sitespeedio/browsertime/pull/1803
> add wait.byCondition method documentation

- lib/plugins/browsertime/analyzer.js
https://github.com/sitespeedio/sitespeed.io/issues/3682
> Fix preWarmServer.

- lib/plugins/analysisstorer/index.js
https://github.com/sitespeedio/sitespeed.io/issues/3701
> Ignore axe setup message when storing data.

- lib/plugins/influxdb/cli.js
- lib/plugins/influxdb/index.js
- lib/plugins/influxdb/senderV2.js
- npm-shrinkwrap.json
- package.json
Add support for Influxdb version 2
Should close  #3197
> Add support for influxDBV2

- lib/plugins/html/templates/url/metrics/inp.pug
- npm-shrinkwrap.json
- package.json
New Browsertime with updated INP collection.
> Updated INP

- docker/docker-compose.yml
It's a not big deal, but I decided to fix it.
> Docker compose: grammar fix

- docker/docker-compose.yml
- docker/grafana/provisioning/dashboards/ChromeUserExperienceReport.json
- docker/grafana/provisioning/dashboards/Leaderboard.json
- docker/grafana/provisioning/dashboards/PageMetrics.json
- docker/grafana/provisioning/dashboards/Plus1.json
- docker/grafana/provisioning/dashboards/Welcome.json
- docker/grafana/provisioning/dashboards/WikipediaLogin.json
- docker/grafana/provisioning/dashboards/default.yaml
- docker/grafana/provisioning/datasources/graphite.yaml
- docker/grafana/provisioning/datasources/json.yaml
https://github.com/sitespeedio/sitespeed.io/issues/3916
> Move dashboards to main repo

- lib/plugins/axe/index.js
- lib/plugins/axe/pug/index.pug
- lib/plugins/browsertime/index.js
> Display axe version on summary page

- bin/browsertimeWebPageReplay.js
Add support for --verbose and enabling Chromedriver logs.
> Enable logging for WebPageReplay recording phase

- lib/plugins/sustainable/helper.js
- lib/plugins/sustainable/index.js
- npm-shrinkwrap.json
- package.json
See https://github.com/thegreenwebfoundation/co2.js/issues/182
> Move functionality from co2 to sitespeed.io.

- lib/plugins/influxdb/data-generator.js
https://github.com/sitespeedio/sitespeed.io/issues/3997
> Fix rsd Influx.

- lib/support/friendlynames.js
https://github.com/sitespeedio/sitespeed.io/issues/3947
> Fix showing sustainable metrics in pages page.

- docs/documentation/sitespeed.io/s3/index.md
https://github.com/sitespeedio/sitespeed.io/issues/3919
> docs: add cors documentation example

- bin/sitespeed.js
https://github.com/sitespeedio/sitespeed.io/issues/4062
> Fix supressing the budget

- lib/plugins/sustainable/index.js
- npm-shrinkwrap.json
- package.json
https://github.com/sitespeedio/sitespeed.io/issues/4073
> Upgrade to co2 0.14.2

- lib/plugins/browsertime/index.js
- lib/plugins/html/templates/url/thirdparty/index.pug
https://github.com/sitespeedio/sitespeed.io/issues/4078
> A more solid error handling.

- npm-shrinkwrap.json
- package.json
The new version, has a new updated version of the Chromedriver installation that fixed the bug installing on Windows, reported in https://github.com/sitespeedio/sitespeed.io/issues/4095
> Browsertime 21.3.1

- lib/plugins/html/setup/summaryBoxesDefaultLimits.js
https://github.com/sitespeedio/sitespeed.io/issues/4119
> Set default limits for CLS and TTFB

- lib/plugins/influxdb/data-generator.js
https://github.com/sitespeedio/sitespeed.io/issues/4137
> Add new tag: axeType for axe data in InfluxDB.

- bin/sitespeed.js
https://github.com/sitespeedio/sitespeed.io/issues/4159
> Increase number listeners before you get a warning

- docs/documentation/sitespeed.io/configuration/config.md
Remove extra space in the `scp` section
> Update config documentation

- lib/plugins/s3/index.js
https://github.com/sitespeedio/sitespeed.io/issues/4117#issuecomment-2149346616
> s3: add missing extra options

- lib/plugins/browsertime/analyzer.js
Fixes https://github.com/sitespeedio/sitespeed.io/issues/4178
> Make sure extra run runs after the engine stopped 

- npm-shrinkwrap.json
- package.json
Lets of a follow up and add version and rating:
https://www.thegreenwebfoundation.org/news/release-guide-co2-js-v0-16/
> co2 0.16.0

- lib/plugins/browsertime/index.js
https://github.com/sitespeedio/sitespeed.io/issues/4228
> Guard against disabling screenshots.

- docs/_posts/2024-06-04-onlinetest.md
Fix added for Issue - https://github.com/sitespeedio/sitespeed.io/issues/4247
> Fix broken link for onlinetest blog

- lib/plugins/browsertime/analyzer.js
https://github.com/sitespeedio/sitespeed.io/issues/4258
> Add requestheaders and cookie info to prewarm server.

- Dockerfile
See https://bugzilla.mozilla.org/show_bug.cgi?id=1930110
> Revert to Firefox 131

- Dockerfile
Lets FF 132 run again on a test server.
> Try out FF 132 again

- docs/documentation/sitespeed.io/browsers/index.md
Small PR - adjusts the `firefoxPreferences.js` reference in `docs/documentation/sitespeed.io/browsers/index.md`.
> docs: update `firefoxPreferences.js` reference

- lib/plugins/compare/helper.js
This catches if we got no longtask information.
> fix: use compare with --cpu for Firefox failed.

- lib/plugins/compare/statistical.py
Add validation for prevent an error from the Wilcoxon test when dataset has different number of values.
> [Compare] Add validation for dataset lengths for the Wilcoxon test.

- .dockerignore
- Dockerfile
- Dockerfile-slim
- lib/plugins/sustainable/index.js
- npm-shrinkwrap.json
- package.json
- tools/postinstall.js
The URL2green file is becoming larger and larger. Skip downloading it if you don't specifically ask for it.
> Only download url2green when asked for.

- lib/plugins/budget/tap.js
- npm-shrinkwrap.json
- package.json
This remove the Tape dependency and change how we write Tap:
* Always write both success and failures.
* Skip the error trace since it do not add any extra information.
> Remove Tape dependencies.

- lib/plugins/pagexray/index.js
- lib/plugins/pagexray/pagexrayAggregator.js
https://github.com/sitespeedio/sitespeed.io/issues/4453 https://github.com/sitespeedio/sitespeed.io/pull/4454
> Make sure sitespeed.io do not fail if a page fails.

- Dockerfile
Reverts sitespeedio/sitespeed.io#4467
> Revert "Chrome 134, Firefox 136, Edge 133"

- lib/support/annotationsHelper.js
See https://github.com/sitespeedio/sitespeed.io/issues/4485
> Be safe when checking for InfluxDB

- lib/plugins/s3/index.js
https://github.com/sitespeedio/sitespeed.io/issues/4501
> s3: make sure Expires always is a Date.
